import { useState } from 'react';
import { KeyboardAvoidingView, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { Page } from '../components/TabShell';
import { Button, Chip, IconButton, Sheet, ui } from '../components/ui';
import { RATES, type Currency } from '../lib/constants';
import { convert } from '../lib/converter';
import { colors, numbers, type } from '../theme';
const currencies=Object.keys(RATES).filter((key):key is Currency=>key in RATES);
export default function Converter(){const [amount,setAmount]=useState(''),[from,setFrom]=useState<Currency>('AUD'),[to,setTo]=useState<Currency>('IDR'),[picker,setPicker]=useState<'from'|'to'|null>(null),[recent,setRecent]=useState<Currency[]>([]);const value=Number(amount),result=Number.isFinite(value)?convert(value,from,to):0;function target(c:Currency){setTo(c);setRecent(r=>[c,...r.filter(x=>x!==c)].slice(0,3));}return <Page title="Currency converter" back needsData={false}><KeyboardAvoidingView behavior="padding" style={ui.flex}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={[ui.gutter,{paddingTop:30,paddingBottom:30}]}><View style={[ui.card,{padding:16}]}><View style={ui.line}><Text style={[type.label,ui.flex]}>From</Text><Chip label={`${from} ⌄`} onPress={()=>setPicker('from')}/></View><TextInput accessibilityLabel="Amount to convert" autoFocus keyboardType="decimal-pad" value={amount} onChangeText={setAmount} placeholder="0.00" placeholderTextColor={colors.ink3} style={[type.title,numbers,{minHeight:70,fontSize:34,textAlign:'right',color:colors.ink}]}/></View><View style={{alignItems:'center',marginBottom:16}}><IconButton name="swap" label="Swap currencies" onPress={()=>{const previous=from;setFrom(to);target(previous);}}/></View><View style={[ui.card,{padding:16}]}><View style={ui.line}><Text style={[type.label,ui.flex]}>To</Text><Chip label={`${to} ⌄`} onPress={()=>setPicker('to')}/></View><Text selectable style={[type.title,numbers,{fontSize:34,textAlign:'right',paddingVertical:20,color:colors.moss}]}>{new Intl.NumberFormat('en-AU',{maximumFractionDigits:to==='IDR'||to==='JPY'||to==='KRW'?0:2,minimumFractionDigits:to==='IDR'||to==='JPY'||to==='KRW'?0:2}).format(result)}</Text><Text style={[type.subtitle,{textAlign:'right'}]}>stored rate, not live</Text></View>{recent.length>0&&<><Text style={ui.label}>Recent targets</Text><View style={ui.wrap}>{recent.map(c=><Chip key={c} label={c} selected={c===to} onPress={()=>target(c)}/>)}</View></>}</ScrollView></KeyboardAvoidingView>{picker&&<Sheet title="Currency" onClose={()=>setPicker(null)}>{currencies.map(c=><Pressable key={c} accessibilityRole="button" onPress={()=>{if(picker==='from')setFrom(c);else target(c);setPicker(null);}} style={ui.editRow}><Text style={[type.body,numbers,ui.flex]}>{c}</Text><Text style={[type.subtitle,numbers]}>{c===(picker==='from'?from:to)?'Selected':''}</Text></Pressable>)}</Sheet>}</Page>;}
