export const defaultState = {
  events: [
    { id: 1, title: 'Robotics Sub-Group B', date: '2025-04-30', start: '14:00', end: '15:30', cat: 'work',     notes: 'ALFWorld pipeline' },
    { id: 2, title: 'Gym',                  date: '2025-05-01', start: '07:00', end: '08:00', cat: 'personal', notes: '' },
    { id: 3, title: 'KASA Meeting',         date: '2025-05-02', start: '18:00', end: '19:30', cat: 'personal', notes: '' },
    { id: 4, title: 'Assignment Due',       date: '2025-05-05', start: '23:59', end: '23:59', cat: 'google',   notes: '' },
  ],
  expenses: [
    { id: 1,    date: '2025-02-01', cat: 'Transport', detail: 'Fuel',            cost: 42,     type: 'normal', person: '' },
    { id: 2,    date: '2025-02-01', cat: 'Recurring', detail: 'Spotify',         cost: 3.5,    type: 'normal', person: '' },
    { id: 3,    date: '2025-02-01', cat: 'Recurring', detail: 'Apple iCloud',    cost: 7.5,    type: 'normal', person: '' },
    { id: 4,    date: '2025-02-05', cat: 'Food',      detail: 'Pafu',            cost: 5.2,    type: 'normal', person: '' },
    { id: 5,    date: '2025-02-05', cat: 'Food',      detail: 'Charrd',          cost: 16,     type: 'normal', person: '' },
    { id: 6,    date: '2025-02-06', cat: 'Transport', detail: 'Fuel',            cost: 28.33,  type: 'normal', person: '' },
    { id: 'h1', isHeader: true,     label: 'KASA Retreat',     date: '2025-02-07' },
    { id: 7,    date: '2025-02-07', cat: 'Food',      detail: 'Branch',          cost: 21,     type: 'normal', person: '' },
    { id: 8,    date: '2025-02-07', cat: 'Food',      detail: 'Froyo',           cost: 10.36,  type: 'paid',   person: 'Duleesha' },
    { id: 9,    date: '2025-02-07', cat: 'Food',      detail: 'Coffee',          cost: 4.95,   type: 'normal', person: '' },
    { id: 10,   date: '2025-02-07', cat: 'Food',      detail: 'HSP',             cost: 12,     type: 'normal', person: '' },
    { id: 11,   date: '2025-02-08', cat: 'Misc',      detail: 'Retreat Expenses',cost: 112.11, type: 'normal', person: '' },
    { id: 'e1', isEnd: true,        label: 'End of KASA Retreat', date: '2025-02-08' },
    { id: 12,   date: '2025-02-11', cat: 'Misc',      detail: 'CapCut Pro',      cost: 70,     type: 'normal', person: '' },
    { id: 13,   date: '2025-02-15', cat: 'Transport', detail: 'Fuel',            cost: 22.03,  type: 'normal', person: '' },
    { id: 14,   date: '2025-02-16', cat: 'Food',      detail: 'KFC',             cost: 3.95,   type: 'normal', person: '' },
    { id: 15,   date: '2025-02-19', cat: 'Food',      detail: 'Hanaichi',        cost: 13.4,   type: 'normal', person: '' },
    { id: 16,   date: '2025-02-19', cat: 'Food',      detail: 'Laguna',          cost: 1.79,   type: 'for',    person: 'Raph' },
    { id: 17,   date: '2025-02-20', cat: 'Misc',      detail: 'DJI Mic mini',    cost: 125.88, type: 'normal', person: '' },
    { id: 18,   date: '2025-02-21', cat: 'Food',      detail: 'GYG',             cost: 12,     type: 'normal', person: '' },
    { id: 19,   date: '2025-02-23', cat: 'Transport', detail: 'Fuel',            cost: 37.12,  type: 'normal', person: '' },
  ],
  income: [
    { id: 1, date: '2025-02-02', source: 'ING Bank Bonus', amount: 125,    salary: false },
    { id: 2, date: '2025-02-17', source: 'CNY',            amount: 100,    salary: false },
    { id: 3, date: '2025-02-25', source: 'Allied',         amount: 271.73, salary: true  },
  ],
  debts: [
    { id: 1, date: '2025-07-13', person: 'Kevin',  detail: 'half the Airbnb',       amount: 220,   resolved: false, resolvedAt: null },
    { id: 2, date: '2025-08-28', person: 'Sarah',  detail: 'concert ticket',        amount: 95,    resolved: false, resolvedAt: null },
    { id: 3, date: '2025-09-09', person: 'Jess',   detail: 'brunch',                amount: 28,    resolved: true,  resolvedAt: '2025-09-12' },
    { id: 4, date: '2025-08-30', person: 'Kevin',  detail: 'flights',               amount: 640,   resolved: true,  resolvedAt: '2025-09-01' },
  ],
  habits: [
    { id: 1, name: 'Reach out x2',    type: 'weekly', goal: 2, daily: false },
    { id: 2, name: 'Meet people x2',  type: 'weekly', goal: 2, daily: false },
    { id: 3, name: 'LeetCode x3',     type: 'weekly', goal: 3, daily: false },
    { id: 4, name: 'Gym x3',          type: 'weekly', goal: 3, daily: false },
    { id: 5, name: 'Post content',    type: 'daily',  goal: 7, daily: true  },
    { id: 6, name: 'Physical exercise', type: 'daily', goal: 7, daily: true },
  ],
  habitChecks: {},
  habitWeekOffset: 0,
  pillars: [
    { id: 1, name: 'DITL',              colorIdx: 4 },
    { id: 2, name: 'Thought/Feeling',   colorIdx: 2 },
    { id: 3, name: 'Minimalistic Vlog', colorIdx: 5 },
    { id: 4, name: 'Story Telling',     colorIdx: 0 },
    { id: 5, name: 'Talking Head',      colorIdx: 1 },
  ],
  content: [
    { id: 1,  idea: 'DITL2',              pillarId: 1, status: 'Posted', notes: '', postDate: '', refUrl: '', twist: '', origScript: '', script: '' },
    { id: 2,  idea: 'Charrd Burger run',  pillarId: 1, status: 'Posted', notes: '', postDate: '', refUrl: '', twist: '', origScript: '', script: '' },
    { id: 3,  idea: 'Family spend time',  pillarId: 2, status: 'Posted', notes: '', postDate: '', refUrl: '', twist: '', origScript: '', script: '' },
    { id: 4,  idea: 'DITL3',              pillarId: 1, status: 'Edited', notes: 'dk if still wanna post', postDate: '2026-09-21', refUrl: '', twist: '', origScript: '', script: 'VO: 6am. Gym, then desk.\nB-roll: coffee, standing desk, commit screen, walk.\nClose on: what I shipped today.' },
    { id: 5,  idea: 'KASA intro',         pillarId: 3, status: 'Idea',   notes: '', postDate: '', refUrl: '', twist: '', origScript: '', script: '' },
    { id: 6,  idea: 'no 20k',             pillarId: 4, status: 'Posted', notes: '', postDate: '', refUrl: '', twist: '', origScript: '', script: '' },
    { id: 7,  idea: 'explore more things',pillarId: 3, status: 'Idea',   notes: '', postDate: '2026-09-28', refUrl: '', twist: '', origScript: '', script: '' },
    { id: 8,  idea: 'no one feels ahead', pillarId: 2, status: 'Posted', notes: '', postDate: '', refUrl: '', twist: '', origScript: '', script: '' },
    { id: 9,  idea: 'NEW MIC',            pillarId: 3, status: 'Posted', notes: '', postDate: '', refUrl: '', twist: '', origScript: '', script: '' },
    { id: 10, idea: 'life comes in waves',pillarId: 4, status: 'Scripted', notes: '', postDate: '2026-09-23', refUrl: 'https://instagram.com/reel/EXAMPLE1', twist: 'Theirs is about grief. Mine: startup momentum. Same wave metaphor, founder stakes, ends on a question.', origScript: 'HOOK: Nobody tells you grief comes in waves.\n\nSome days the water is flat. You think you are fine.\n\nThen a song plays in the grocery store and you are under again.\n\nCLOSE: The waves do not stop. You just get better at swimming.', script: 'HOOK: Nobody tells you building comes in waves.\n\nSome weeks everything ships. You think you cracked it.\n\nThen one bad launch and you are under again.\n\nCLOSE: The waves do not stop. You just stop quitting at low tide.\n\nQ: What was your lowest tide this year?' },
    { id: 11, idea: 'money while young',  pillarId: 4, status: 'Idea',   notes: '', postDate: '', refUrl: '', twist: '', origScript: '', script: '' },
    { id: 12, idea: 'Cleaning Desk',      pillarId: 1, status: 'Posted', notes: '', postDate: '', refUrl: '', twist: '', origScript: '', script: '' },
    { id: 13, idea: 'no 20k pt 2',        pillarId: 5, status: 'Posted', notes: '', postDate: '', refUrl: '', twist: '', origScript: '', script: '' },
  ],
  contentFilter: 'all',
  nextId: 200,
}
