import { useState } from 'react';
import { Pressable, RefreshControl, SectionList, Text, View } from 'react-native';
import ReanimatedSwipeable from 'react-native-gesture-handler/ReanimatedSwipeable';
import { Page } from '../../../components/TabShell';
import { Button, EmptyState, Fab, ui } from '../../../components/ui';
import { IncomeSheet } from '../../../components/sheets/IncomeSheet';
import { useData } from '../../../hooks/useAppData';
import { useActions } from '../../../hooks/useActions';
import { dateLabel, money, monthLabel } from '../../../lib/format';
import type { Id, Income } from '../../../lib/types';
import { colors, numbers, type } from '../../../theme';
export default function IncomeScreen(){const data=useData(),actions=useActions(),[sheet,setSheet]=useState<Id|'new'|null>(null);const months=[...new Set(data.state.income.map(i=>i.date.slice(0,7)))].sort().reverse(),sections=months.map(month=>({month,data:data.state.income.filter(i=>i.date.startsWith(month)).sort((a,b)=>b.date.localeCompare(a.date))}));const income=data.state.income.find(i=>i.id===sheet);return <Page title="Income" back><SectionList<Income> sections={sections} keyExtractor={i=>String(i.id)} contentContainerStyle={[ui.gutter,{paddingBottom:100}]} stickySectionHeadersEnabled refreshControl={<RefreshControl refreshing={false} onRefresh={data.refetch} tintColor={colors.moss}/>} renderSectionHeader={({section})=><View style={[ui.line,{paddingVertical:13,backgroundColor:colors.paper}]}><Text style={[type.label,numbers,ui.flex]}>{monthLabel(section.month)}</Text><Text style={[type.label,numbers]}>{money(section.data.reduce((s,i)=>s+i.amount,0))}</Text></View>} renderItem={({item,index,section})=><ReanimatedSwipeable renderRightActions={()=> <Button label="Delete" tone="danger" disabled={actions.busy} onPress={()=>actions.deleteIncome(item.id)}/>}><Pressable accessibilityRole="button" onPress={()=>setSheet(item.id)} style={[ui.line,{minHeight:64,paddingHorizontal:14,paddingVertical:9,backgroundColor:colors.surface,borderBottomWidth:1,borderColor:colors.border,borderTopLeftRadius:index===0?14:0,borderTopRightRadius:index===0?14:0,borderBottomLeftRadius:index===section.data.length-1?14:0,borderBottomRightRadius:index===section.data.length-1?14:0}]}><View style={ui.flex}><Text style={type.body}>{item.source}</Text><View style={ui.line}><Text style={[type.subtitle,numbers]}>{dateLabel(item.date,false)}</Text>{item.salary&&<Text style={[type.label,{color:colors.green,backgroundColor:colors.greenLight,padding:4,borderRadius:6}]}>salary</Text>}</View></View><Text style={[type.sheetTitle,numbers,{color:colors.green}]}>{money(item.amount)}</Text></Pressable></ReanimatedSwipeable>} ListEmptyComponent={<EmptyState title="No income logged yet" copy="Add income to see where it came from, grouped by month." action="Add income" onPress={()=>setSheet('new')}/>}/><Fab label="Add income" onPress={()=>setSheet('new')}/>{sheet!==null&&(sheet==='new'||income)&&<IncomeSheet income={income} onClose={()=>setSheet(null)}/>}</Page>;}
