import { useState } from 'react';
import { ScrollView, Text, useWindowDimensions, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { BarChart, PieChart } from 'react-native-gifted-charts';
import { Page } from '../../../components/TabShell';
import { Chip, ui } from '../../../components/ui';
import { useData } from '../../../hooks/useAppData';
import { CATS, CAT_COLORS, type Category } from '../../../lib/constants';
import { dateString, money, monthLabel } from '../../../lib/format';
import type { Expense } from '../../../lib/types';
import { colors, numbers, type } from '../../../theme';
export default function Insights(){
 const data=useData(),params=useLocalSearchParams<{month?:string;wholeYear?:string}>(),month=params.month??dateString().slice(0,7),year=month.slice(0,4),period=params.wholeYear==='true'?year:month,[category,setCategory]=useState<Category|'all'>('all'),{width}=useWindowDimensions();
 const expenses=data.state.expenses.filter((row):row is Expense=>!row.isHeader&&!row.isEnd),periodRows=expenses.filter(row=>row.date.startsWith(period));
 const totals=CATS.map(cat=>({cat,value:periodRows.filter(row=>row.cat===cat).reduce((s,row)=>s+row.cost,0)})).filter(row=>row.value>0).sort((a,b)=>b.value-a.value),total=totals.reduce((s,r)=>s+r.value,0),yearRows=expenses.filter(row=>row.date.startsWith(year)&&(category==='all'||row.cat===category)),yearTotals=CATS.map(cat=>({cat,value:yearRows.filter(r=>r.cat===cat).reduce((s,r)=>s+r.cost,0)})).filter(r=>r.value>0).sort((a,b)=>b.value-a.value);
 const stackData=Array.from({length:12},(_,i)=>{const key=`${year}-${String(i+1).padStart(2,'0')}`,rows=yearRows.filter(r=>r.date.startsWith(key)),sum=rows.reduce((s,r)=>s+r.cost,0),current=key===dateString().slice(0,7);return {stacks:(category==='all'?CATS:[category]).map(cat=>({value:rows.filter(r=>r.cat===cat).reduce((s,r)=>s+r.cost,0),color:CAT_COLORS[cat]})),label:'JFMAMJJASOND'[i],labelTextStyle:{...type.label,...numbers,color:current?colors.ink:colors.ink3},...(current?{topLabelComponent:()=> <Text style={[type.label,numbers,{fontSize:11,color:colors.ink}]}>{money(sum)}</Text>}: {})};});
 function legend(rows:typeof totals,percent=false){return rows.map(row=><View key={row.cat} style={[ui.line,{minHeight:32}]}><View style={{width:9,height:9,borderRadius:5,backgroundColor:CAT_COLORS[row.cat]}}/><Text style={[type.subtitle,ui.flex]}>{row.cat}</Text><Text style={[type.body,numbers]}>{money(row.value)}</Text>{percent&&<Text style={[type.label,numbers,{minWidth:35,textAlign:'right'}]}>{Math.round(row.value/total*100)}%</Text>}</View>);}
 return <Page title="Insights" back><ScrollView contentContainerStyle={[ui.gutter,{paddingTop:16,paddingBottom:30}]}><View style={[ui.card,{padding:15}]}><View style={[ui.line,{marginBottom:18}]}><Text style={[type.body,ui.flex,numbers]}>By category · {period.length===4?year:monthLabel(month)}</Text><Text style={[type.body,numbers]}>{money(total)}</Text></View>{total>0?<View accessible accessibilityLabel={`Spending by category. ${totals.slice(0,3).map(r=>`${r.cat}, ${money(r.value)}`).join('. ')}`}><View style={{alignItems:'center',marginBottom:14}}><PieChart donut data={totals.map(r=>({value:r.value,color:CAT_COLORS[r.cat]}))} radius={85} innerRadius={64} innerCircleColor={colors.surface} centerLabelComponent={()=> <View style={{alignItems:'center',maxWidth:110}}><Text style={type.label}>Biggest category</Text><Text style={[type.body,{marginTop:4}]}>{totals[0]?.cat}</Text></View>}/></View>{legend(totals)}</View>:<Text style={type.subtitle}>No spending in this period.</Text>}</View>
 <View style={[ui.card,{padding:15}]}><Text style={[type.body,numbers,{marginBottom:18}]}>Month by month, {year}</Text><View accessible accessibilityLabel={`Yearly spending. ${yearTotals.slice(0,3).map(r=>`${r.cat}, ${money(r.value)}`).join('. ')}`}><BarChart stackData={stackData} width={Math.max(200,width-97)} height={140} barWidth={13} spacing={9} initialSpacing={4} endSpacing={4} noOfSections={3} maxValue={Math.max(1,...stackData.map(r=>r.stacks.reduce((s,x)=>s+x.value,0)))*1.2} formatYLabel={value => Number(value).toFixed(2)} hideRules yAxisThickness={0} xAxisThickness={0} yAxisTextStyle={[type.label,numbers]} isAnimated={false}/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={[ui.line,{paddingVertical:12}]}><Chip label="All categories" selected={category==='all'} onPress={()=>setCategory('all')}/>{CATS.map(cat=><Chip key={cat} label={cat} selected={category===cat} onPress={()=>setCategory(category===cat?'all':cat)}/>)}</ScrollView>{legend(yearTotals)}</View>
 <View style={[ui.card,{padding:15}]}><Text style={[type.body,{marginBottom:12}]}>{period.length===4?'Year':monthLabel(month).split(' ')[0]} totals</Text>{legend(totals,true)}<View style={[ui.line,{borderTopWidth:1,borderColor:colors.border,marginTop:12,paddingTop:12}]}><Text style={[type.body,ui.flex]}>Total out</Text><Text style={[type.body,numbers]}>{money(total)}</Text></View></View></ScrollView></Page>;
}
